/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlocklistUpdateResult {
  'newBlocklist' : Array<string>,
  'message' : string,
  'success' : boolean,
}
export interface CustomDomainConfig {
  'status' : CustomDomainStatus,
  'desiredDomain' : string,
  'instructions' : string,
  'canonicalUrl' : string,
  'dnsSetupHelp' : string,
  'requirements' : string,
}
export interface CustomDomainConfigUpdate {
  'status' : CustomDomainStatus,
  'instructions' : string,
  'canonicalUrl' : string,
  'requirements' : string,
}
export type CustomDomainStatus = { 'pending' : null } |
  { 'error' : string } |
  { 'configured' : null };
export interface PrivacySettings {
  'blockList' : Array<string>,
  'autoStopTracking' : boolean,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBlockEntry' : ActorMethod<[string], BlocklistUpdateResult>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomDomainConfig' : ActorMethod<[], [] | [CustomDomainConfig]>,
  'getPrivacySettings' : ActorMethod<[], PrivacySettings>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'proposeCustomDomain' : ActorMethod<[string], undefined>,
  'removeBlockEntry' : ActorMethod<[string], BlocklistUpdateResult>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAutoStopTracking' : ActorMethod<[boolean], undefined>,
  'updateCustomDomainConfig' : ActorMethod<
    [CustomDomainConfigUpdate],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];