/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BlocklistUpdateResult = IDL.Record({
  'newBlocklist' : IDL.Vec(IDL.Text),
  'message' : IDL.Text,
  'success' : IDL.Bool,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CustomDomainStatus = IDL.Variant({
  'pending' : IDL.Null,
  'error' : IDL.Text,
  'configured' : IDL.Null,
});
export const CustomDomainConfig = IDL.Record({
  'status' : CustomDomainStatus,
  'desiredDomain' : IDL.Text,
  'instructions' : IDL.Text,
  'canonicalUrl' : IDL.Text,
  'dnsSetupHelp' : IDL.Text,
  'requirements' : IDL.Text,
});
export const PrivacySettings = IDL.Record({
  'blockList' : IDL.Vec(IDL.Text),
  'autoStopTracking' : IDL.Bool,
});
export const CustomDomainConfigUpdate = IDL.Record({
  'status' : CustomDomainStatus,
  'instructions' : IDL.Text,
  'canonicalUrl' : IDL.Text,
  'requirements' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBlockEntry' : IDL.Func([IDL.Text], [BlocklistUpdateResult], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomDomainConfig' : IDL.Func(
      [],
      [IDL.Opt(CustomDomainConfig)],
      ['query'],
    ),
  'getPrivacySettings' : IDL.Func([], [PrivacySettings], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'proposeCustomDomain' : IDL.Func([IDL.Text], [], []),
  'removeBlockEntry' : IDL.Func([IDL.Text], [BlocklistUpdateResult], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAutoStopTracking' : IDL.Func([IDL.Bool], [], []),
  'updateCustomDomainConfig' : IDL.Func([CustomDomainConfigUpdate], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BlocklistUpdateResult = IDL.Record({
    'newBlocklist' : IDL.Vec(IDL.Text),
    'message' : IDL.Text,
    'success' : IDL.Bool,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CustomDomainStatus = IDL.Variant({
    'pending' : IDL.Null,
    'error' : IDL.Text,
    'configured' : IDL.Null,
  });
  const CustomDomainConfig = IDL.Record({
    'status' : CustomDomainStatus,
    'desiredDomain' : IDL.Text,
    'instructions' : IDL.Text,
    'canonicalUrl' : IDL.Text,
    'dnsSetupHelp' : IDL.Text,
    'requirements' : IDL.Text,
  });
  const PrivacySettings = IDL.Record({
    'blockList' : IDL.Vec(IDL.Text),
    'autoStopTracking' : IDL.Bool,
  });
  const CustomDomainConfigUpdate = IDL.Record({
    'status' : CustomDomainStatus,
    'instructions' : IDL.Text,
    'canonicalUrl' : IDL.Text,
    'requirements' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBlockEntry' : IDL.Func([IDL.Text], [BlocklistUpdateResult], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomDomainConfig' : IDL.Func(
        [],
        [IDL.Opt(CustomDomainConfig)],
        ['query'],
      ),
    'getPrivacySettings' : IDL.Func([], [PrivacySettings], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'proposeCustomDomain' : IDL.Func([IDL.Text], [], []),
    'removeBlockEntry' : IDL.Func([IDL.Text], [BlocklistUpdateResult], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAutoStopTracking' : IDL.Func([IDL.Bool], [], []),
    'updateCustomDomainConfig' : IDL.Func([CustomDomainConfigUpdate], [], []),
  });
};

export const init = ({ IDL }) => { return []; };